spring.application.name=beautique

# database configuration

# URL de conexão (padrão do Postgres é a porta 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/beautique
spring.datasource.username=postgres
spring.datasource.password=1712
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
